### ISSUE TITLE
It doesn't work with new Red5 version

### ISSUE THREAD

**Issue by NlsNi** [Red5/red5-rtsp-restreamer#4]
I could not find  the `StreamingProxy `  in new version. I tried to import package `org.red5.proxy.StreamingProxy`  and `org.red5.server.stream.StreamingProxy` .But it doesn't work, the two packages don't exist. Are there any alternative  ways to restreaming a live stream?Manual or docmention will help.Thanks a lot.

**Comment by mondain** [comment]
That class is in the red5-client source here: https://github.com/Red5/red5-client/blob/master/src/main/java/org/red5/proxy/StreamingProxy.java
