### ISSUE TITLE
Not able to compile and deploy on server

### ISSUE THREAD

**Issue by MuhammadAasharib** [Red5/red5-rtsp-restreamer#5]
There is almost no documentation. i am having difficulty in compiling the app and deploy on server. Please tell me how can i compile it and deploy on server

**Comment by Andy--S** [comment]
Which rtsp restreamer?  The older plugin i do not believe was maintained.

**Comment by mondain** [comment]
@MuhammadAasharib this is not / has not been maintained due to resources. If you'd like a ready-to-use RTSP solution, please contact Red5 Pro at https://www.red5pro.com/
